### ISSUE TITLE
Open camera issue

### ISSUE THREAD

**Issue by danielcardeenas** [jkwiecien/EasyImage#1]
When trying to open camera 
`EasyImage.openCamera(this);`

This happens

```
W/System.err: java.io.IOException: open failed: ENOENT (No such file or directory)
W/System.err:     at java.io.File.createNewFile(File.java:939)
W/System.err:     at java.io.File.createTempFile(File.java:1004)
W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.openCamera(EasyImage.java:59)
```

**Comment by jkwiecien** [comment]
Have you declared permission as stated in the setup?

**Comment by tajchert** [comment]
Got same issue, on Android 6.0 - Nexus 5.
Custom camera logic is working fine, EasyImage - exception.
Permission is there.

**Comment by tajchert** [comment]
Fixed - wrapped EasyImage with Nammu library (https://github.com/tajchert/Nammu). As you need to ask for `Manifest.permission.WRITE_EXTERNAL_STORAGE`.

**Comment by jkwiecien** [comment]
Oh yeah, As stated in the description I haven't addressed RuntimePermissions yet. Will do soon.

**Comment by jkwiecien** [comment]
Documented what's necessary for Android 6.0 and higher in the readme
