### ISSUE TITLE
Canceling a taken Photo leads to wrong ImageSource in onCanceled callback

### ISSUE THREAD

**Issue by C0nstan** [jkwiecien/EasyImage#100]
If i open the chooser via 
`EasyImage.openChooserWithGallery`
and pick camera to take a photo, i get the wrong ImageSurce "DOCUMENTS" if i cancel it.

So this piece of Code did not work.
` if (source == EasyImage.ImageSource.CAMERA) {
                    File photoFile = EasyImage.lastlyTakenButCanceledPhoto(getActivity());
                    if (photoFile != null) photoFile.delete();
                }`

**Comment by jkwiecien** [comment]
Merged and released in 2.0.1
