### ISSUE TITLE
EasyImage/2.0.1 build

### ISSUE THREAD

**Issue by C0nstan** [jkwiecien/EasyImage#102]
Log https://jitpack.io/com/github/jkwiecien/EasyImage/2.0.1/build.log

**Comment by jitpack-io** [comment]
Hi @C0nstan 

There are some compile errors in the log

**Comment by C0nstan** [comment]
Yeah i know, but i need it to be fixed :/
Dont want to import the lib as sources to fix it by myself.

**Comment by jitpack-io** [comment]
Perhaps it can be fixed by the maintainers
/cc @jkwiecien

**Comment by jkwiecien** [comment]
I'll fix it in 2.0.2
