### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by Bahramudin** [jkwiecien/EasyImage#104]
I have added this "compile 'com.github.jkwiecien:EasyImage:1.3.1'" in gradle dependencies but is not working, the gradle sync failed, it is why? 
It is the message:

> Error:(32, 13) Failed to resolve: com.github.jkwiecien:EasyImage:1.3.1

**Comment by ChetanCul** [comment]
You should use the latest version (v2.0.2) of the library unless your app supports lower versions than API 15.
You can get it from jitPack
First add the jitPack repository to your build file -

> 
> allprojects {
> 		repositories {
> 			...//other maven dependencies will go here
> 			maven { url 'https://jitpack.io' }
> 		}
> 	}
> 

now add EasyImage 2.0.2 dependency -

> dependencies {
> 	        compile 'com.github.jkwiecien:EasyImage:2.0.2'
> 	}

You can see other versions [here](https://jitpack.io/#jkwiecien/EasyImage)

**Comment by abbath0767** [comment]
Hey, @jkwiecien if you add this information to README.md in root you save thousand hours)

**Comment by angelopolotto** [comment]
I made a pull request add those instructions: https://github.com/jkwiecien/EasyImage/pull/149
I had the same problem when I was add the EasyImage in my project.

**Comment by IronFuturist** [comment]
Yah, I agree when you update the library version please update ReadMe. Thankfully I found this thread. 

Thanks for making this.
