### ISSUE TITLE
willHandleActivityResult -> Missing scenarios?

### ISSUE THREAD

**Issue by candeiasdan** [jkwiecien/EasyImage#107]
I think you are missing some scenarios on **_willHandleActivityResult_** method.

**Case:** call _openChooserWithGallery()_ or _openChooserWithDocuments()_

**Request codes for these scenarios:** 
RequestCodes.SOURCE_CHOOSER | RequestCodes.PICK_PICTURE_FROM_DOCUMENTS
RequestCodes.SOURCE_CHOOSER | RequestCodes.PICK_PICTURE_FROM_GALLERY

**willHandleActivityResult:**
```
public static boolean willHandleActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == RequestCodes.SOURCE_CHOOSER || requestCode == RequestCodes.PICK_PICTURE_FROM_GALLERY || requestCode == RequestCodes.TAKE_PICTURE || requestCode == RequestCodes.PICK_PICTURE_FROM_DOCUMENTS) {
            return true;
        }
        return false;
    }

```
Here the library doesnt check any of these conditions so the method will return false.
Is this the expected behaviour or are you missing those two checks on IF statement?

Thanks!

**Comment by jkwiecien** [comment]
I think its fixed
