### ISSUE TITLE
Manifest merger failed with multiple error

### ISSUE THREAD

**Issue by nakharin** [jkwiecien/EasyImage#108]
Hello, I need you help this problem.

Merging Errors: Error: Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.emcsthai.ieasy.demo.easyphotopicker.fileprovider) from AndroidManifest.xml:14:13-80 is also present at AndroidManifest.xml:292:13-73 value=(com.emcsthai.ieasy.demo.universalfileprovider). Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:12:9-20:20 to override. app main manifest (this file), line 13 Error: Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/filepaths) from AndroidManifest.xml:19:17-50 is also present at AndroidManifest.xml:297:17-70 value=(@xml/universal_file_provider_paths). Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override. app main manifest (this file), line 18

**Comment by daividssilverio** [comment]
@nakharin 
 I've worked around this by extending the FileProvider class and changing my manifest to:

```XML
<provider
     android:name=".presentation.util.WorkaroundProvider"
     android:authorities="${applicationId}.provider"
     android:exported="false"
     android:grantUriPermissions="true">
     <meta-data
       android:name="android.support.FILE_PROVIDER_PATHS"
       android:resource="@xml/provider_paths" />
</provider>
```

well... it worked

**Comment by PopTudor** [comment]
[this](https://stackoverflow.com/questions/28095703/manifest-merger-failed-error) also worked for me...not sure what it does though

**Comment by jkwiecien** [comment]
I think this is already solved by ExtendedFileProvider class

**Comment by stillie** [comment]
Good day,

I am having the same issue, I have tried this solution, but then the EasyImage library breaks when i apply this solution? Any other way that we can fix this issue?

**Comment by oNguyenVanThanhD** [comment]
I am having the same issue, I fixed it
```
<provider
      ....
      tools:replace="android:authorities"
      >
      <meta-data
          ...
      />
</provider>
```

and
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.xxx"
    xmlns:tools="http://schemas.android.com/tools">
```

**Comment by yongqiangyue** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.xxx"
    **xmlns:tools="http://schemas.android.com/tools"**>
......
<provider
      android:name="android.support.v4.content.FileProvider"
      android:authorities="com...fileprovider"
      android:exported="false"
      android:grantUriPermissions="true"
      **tools:replace="android:authorities"**
      >
      <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/file_paths"
          **tools:replace="android:resource"**
      />
</provider>
