### ISSUE TITLE
use camera without requesting permission at runtime

### ISSUE THREAD

**Issue by zekun-hello** [jkwiecien/EasyImage#109]
Hi, I am playing with the sample app and run it on my phone (API 23). I remove request for permission for WRITE_EXTERNAL_STORAGE and the sample app can still use camera and show the image. Why is it not rejected because of permission not granted?

**Comment by Taig** [comment]
> Starting in API level 19, this permission is not required to read/write files in your application-specific directories returned by getExternalFilesDir(String) and getExternalCacheDir().

https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE
