### ISSUE TITLE
openChooserWithGallery not able to disable multipick

### ISSUE THREAD

**Issue by xbassols** [jkwiecien/EasyImage#113]
Can't find the way to disable the gallery from enabling multiple selection of images.

**Comment by NoHarmDan** [comment]
That appears to be a problem with your gallery app - the library sends a EXTRA_ALLOW_MULTIPLE tag, which is a boolean, which the gallery app ignores. I have the same problem. I believe there is absolutely nothing that can be done with that. That of course applies if you're using the `openGallery(Activity activity, int type, boolean allowMultiple) ` method, I don't think it's possible to use that tag with a chooser.
