### ISSUE TITLE
Save photos to External Storage

### ISSUE THREAD

**Issue by qadirsuh** [jkwiecien/EasyImage#116]
First of all thanks for awesome library.

I want to save the photos to my External Storage.
I have tried like this in onCreate();

```
EasyImageConfiguration config = EasyImage.configuration(this);
        config.setImagesFolderName(Utils.getTodayPhotosDirectory().getAbsolutePath());
        config.setCopyTakenPhotosToPublicGalleryAppFolder(true);

        Log.e("Image Folder", config.getFolderName()); // this returns me => Image Folder: /storage/emulated/0/Emp_Track_Data/14-06-17/Photos // This is correct
```

but `onActivityResult()` I am getting the path

`/data/user/0/enact.employ.tracking/cache/EasyImage/ea229d2c-9f31-4f42-89ee-48d961a47d30-1044389266.jpg`

I want to save images in my own dir.

**Comment by qadirsuh** [comment]
**Update:**

I just checked EasyImage is storing my images to 
/storage/emulated/0/ + "my/dir/folder"

Why its embedding `/storage/emulated/0/` to my path. Its annoying

**Comment by invisible66** [comment]
Did you solved problem?

**Comment by qadirsuh** [comment]
@invisible66  nope

**Comment by jkwiecien** [comment]
It's a system path for images
