### ISSUE TITLE
Can't compile project

### ISSUE THREAD

**Issue by Rehckover** [jkwiecien/EasyImage#117]
Add this line :compile 'com.github.jkwiecien:EasyImage:1.3.1' to the dependecies but always have an error.
Error:Failed to resolve: annotationProcessor
<a href="openFile:D:/Android/The Set-up/app/build.gradle">Open File</a>
Error:(57, 13) Failed to resolve: com.github.jkwiecien:EasyImage:1.3.1
<a href="openFile:D:/Android/The Set-up/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Anrimian** [comment]
Add this to root build.gradle:

repositories {
   maven { url "https://jitpack.io" }
}

It works for me. 
(Found here: https://stackoverflow.com/questions/36252468/cannot-add-external-library-to-android-studio-project)

**Comment by imspikey** [comment]
And check where you include         maven { url 'https://jitpack.io' }
it should be inside allprojects {} not buildscript {}


allprojects {
    repositories {
        jcenter()
        maven { url 'https://jitpack.io' }

    }
}

**Comment by gnumarcelo** [comment]
I've used the current version and it's working fine:
`compile 'com.github.jkwiecien:EasyImage:2.0.3'`
