### ISSUE TITLE
Returned intent is null with camera

### ISSUE THREAD

**Issue by DenisMondon** [jkwiecien/EasyImage#12]
Hi! Thank you for your library! :)

When using EasyImage.openCamera(), the intent resturned is null!
But when using EasyImage.openGalleryPicker(), it is OK!

I've tested on OnePlus One (5.1.1) and Nexus 7 (6.0) with Runtime Permission implemented.

Do you have a similar problem?

Thanks!
Denis

**Comment by DenisMondon** [comment]
My bad sorry, after reading your code, I saw that the image is retrieved from SharedPreferences and not from the intent.

**Comment by o-nos** [comment]
whaaaat
where can I get the taken photo? It's still null in the intent lol
