### ISSUE TITLE
Image picker from recycler adapter

### ISSUE THREAD

**Issue by skined90** [jkwiecien/EasyImage#129]
Is there possibility to use library directly from recycler adapter? 
I'm struggling with the onActivityResult. I can not pass item position to it and add image directly from activity.

**Comment by jkwiecien** [comment]
Use type field when opening any picker, you get it back with `onImagesPicked` callback

**Comment by secreal** [comment]
just add some info, sometimes we use fragment_name.this.getActivity() to pass activity/context.
For this case, if you use fragment_name.this.getActivity() on your recycler adapter, you need to set up OnActivityResult on your activity, but if you use fragment_name.this, you can set up OnActivityResult on your fragment
