### ISSUE TITLE
Garbage file on "Images" folder

### ISSUE THREAD

**Issue by Ceaggar** [jkwiecien/EasyImage#13]
When a user opens the camera, a file is created in the folder "Images", if the user cancels the application, this file is not deleted. 
--
The delegate "onCanceled" does not provide the path to the image to remove it.
--
It would be great if you could rename the folder "Images".
Thank you very much for creating this library, it helps to avoid having to do the same process again and again each time you want to manage images from the gallery or from the camera.

**Comment by jkwiecien** [comment]
I've added method ```EasyImage.lastlyTakenButCanceledPhoto(Context context);``` and presented it's usage in the sample app:

```java
@Override
            public void onCanceled(EasyImage.ImageSource source) {
                //Cancel handling, you might wanna remove taken photo if it was canceled
                if (source == EasyImage.ImageSource.CAMERA) {
                    File photoFile = EasyImage.lastlyTakenButCanceledPhoto(MainActivity.this);
                    if (photoFile != null) photoFile.delete();
                }
            }
```

It has a bottleneck though. User might take several approach to take the perfect photo. Those photos won't be deleted. Only the last canceled photo will be returned. 

Available in the nearest release

**Comment by jkwiecien** [comment]
Also added possibility of changint the folder name with:
```        EasyImage.configuration(this)
                .setImagesFolderName("Sample app images");
```

**Comment by Ceaggar** [comment]
Thank you very much, I feel like I have an extra partner in my work.
