### ISSUE TITLE
EasyImage.openChooserWithGallery issue

### ISSUE THREAD

**Issue by thakersamveg608** [jkwiecien/EasyImage#152]
Should give options in single line.

![screenshot_20180607-113659](https://user-images.githubusercontent.com/26307004/41081572-0217c222-6a49-11e8-8a80-6133a38961b6.jpg)

**Comment by jkwiecien** [comment]
Thats not up to the library. Its system picker.

**Comment by thakersamveg608** [comment]
Ok. Thank you.
