### ISSUE TITLE
Change filepaths.xml name

### ISSUE THREAD

**Issue by romaomatt** [jkwiecien/EasyImage#165]
I was using EasyImage without problems until I had to implement my own `FileProvider` to share images from my app. I followed ["Setting up file sharing"](https://developer.android.com/training/secure-file-sharing/setup-sharing) tutorial and it is recommended to 

> specify the directories, start by creating the file **filepaths.xml** in the res/xml/ subdirectory of your project

When I tried to use EasyImage again, I came across the "Failed to find configured root that contains [...]" exception.

After some research, I found out (thanks to @allonmj) on issue [#73](https://github.com/jkwiecien/EasyImage/issues/73#issuecomment-252117249) that if you just rename your `filepath.xml` file everything comes back to normal. 

So, I suggest you guys to rename your `filepath.xml` file as this is the default name and will avoid some problems in the future.

**Comment by jkwiecien** [comment]
Fixed in https://github.com/jkwiecien/EasyImage/pull/171
