### ISSUE TITLE
openCameraForImage() crash on Samsung, Xiaomi camera

### ISSUE THREAD

**Issue by closw** [jkwiecien/EasyImage#166]
openCameraForImage() open the camera, but pic's not open after tap to "ok", and app is crashing

**Comment by rajextreme9476** [comment]
openCameraForImage() open the camera crash one plus 6T aslo

**Comment by closw** [comment]
Today I found out that this is the case on all devices with its own camera. The device's own camera (with its non-standard functions) is implemented using the old api camera, which is not already supported now. To get around this, you need to implement a check for api cameras, and if it is old, create your own camera activity, how to do this is described in great detail in google docks and on stackoverflow

**Comment by jkwiecien** [comment]
What samsung exactly that happens for? I tested this on S5 with no problem and its really old.

**Comment by closw** [comment]
@jkwiecien for example in Samsung Galaxy S4 GT-I9500 with Android 5.0, and in S9 I know

**Comment by jkwiecien** [comment]
I got S9 myself, doesn't crash for me. Which exact option crash?

śr., 16 sty 2019, 11:40: Ekaterina Silakova <notifications@github.com>
napisał(a):
