### ISSUE TITLE
Can we delete captured image also when its not cancelled?

### ISSUE THREAD

**Issue by RahulSDeshpande** [jkwiecien/EasyImage#172]
The library supports the feature of deleting image if captured but cancelled.

But, can we delete aa image if captured but **NOT** cancelled?

Cheers 💃

**Comment by jkwiecien** [comment]
There's been some changes in this department in the latest versions, basically the method for deleting latest picture disappeared, as I take care of deleting pictures on cancel or error myself BUT the answer to your question is: **No you can't currently.** - However, if you did not choose to save taken photos in the public gallery, all the files are saved in the app temp directory. System should take care of wiping them out.

**Comment by RahulSDeshpande** [comment]
Thanks @jkwiecien !! :)
