### ISSUE TITLE
ClassNotFoundException pl.aprilapps.easyphotopicker.ExtendedFileProvider

### ISSUE THREAD

**Issue by fmohamad** [jkwiecien/EasyImage#178]
Hi, I want to use EasyImage on my app. I have include the dependency on the gradle but when I want to test the app on my device it gave me this error log. Could help me on make this work? Thanks

Device Samsung  A7 Android version 8.0

java.lang.RuntimeException: Unable to get provider pl.aprilapps.easyphotopicker.ExtendedFileProvider: java.lang.ClassNotFoundException: Didn't find class "pl.aprilapps.easyphotopicker.ExtendedFileProvider" on path: DexPathList[[zip file "

**Comment by jkwiecien** [comment]
Looks like a proguard issue. My library is not obfuscated, but you can add this class or just all the classes of my library to proguard config as keep and see what happens
