### ISSUE TITLE
File extension name not coming properly

### ISSUE THREAD

**Issue by kprathap23** [jkwiecien/EasyImage#18]
I try to select the images that i have selected previously or select image from EasyImage folder. sometimes the File extension is not coming.

               @Override
                public void onImagePicked(File imageFile, EasyImage.ImageSource source) {
                    //Handle the image
                    uploadToServer(imageFile);

                }

**Comment by ayushhgoyal** [comment]
Yes it returns filepath without extension sometimes.

**Comment by emmgfx** [comment]
No solutions to this issue? :(

**Comment by anantshah93** [comment]
same problem

**Comment by jkwiecien** [comment]
Duplicate of https://github.com/jkwiecien/EasyImage/issues/37 Questions there, check it out
