### ISSUE TITLE
Different request codes

### ISSUE THREAD

**Issue by eugeneek** [jkwiecien/EasyImage#19]
Need to add support of different request codes. Sample case is if you have more than one ImageView and Button to take picture and show it in ImageView. Need to load specific image to specific ImageView.

**Comment by adamvarhegyi** [comment]
+1

**Comment by DenisMondon** [comment]
+1

**Comment by jkwiecien** [comment]
Would you guys be happy with using Bundle data instead?

**Comment by adamvarhegyi** [comment]
Well for me, yes sure.

**Comment by pavlospt** [comment]
Any progress on this one?

**Comment by jkwiecien** [comment]
Kinda swamped with work lately. Will try incoming week

**Comment by pavlospt** [comment]
@jkwiecien Ok great! Looking forward!

**Comment by jkwiecien** [comment]
Sorry, was about to do that finally and boom, I've broken my hand. Now when I'm partially better I resolved this. Require some testing before I release - release ETA is tomorrow.
