### ISSUE TITLE
Support API 22

### ISSUE THREAD

**Issue by mdagostino** [jkwiecien/EasyImage#20]

**Comment by jkwiecien** [comment]
How is that not supported?

**Comment by mdagostino** [comment]
In the build.gradle file the library uses api 23, and if you use API 22 in your application the library does not compile, I forked the repo and only change that and It worked

**Comment by jkwiecien** [comment]
it's only ```compileSdkVersion``` that is set to 23
You still can set ```compileSdkVersion``` to 23 while ```minSdkVersion``` is set to 14
