### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'

### ISSUE THREAD

**Issue by AlexanderKiyanov** [jkwiecien/EasyImage#203]
Facing an error while trying to build kotlin project:

More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'

What was done:
1. set permissions to the Manifest file
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />

2. set implementation 'com.github.jkwiecien:EasyImage:3.0.3' to app
3. try to compile

**Comment by harloom** [comment]
I also get an error like this

**Comment by ErJeetChaudhary** [comment]
Add this in build.gradle file

packagingOptions {
        exclude 'META-INF/library_release.kotlin_module'
    }
