### ISSUE TITLE
Images from pickers (gallery, document) stored in cache are inaccessible outside

### ISSUE THREAD

**Issue by jfbibeau** [jkwiecien/EasyImage#21]
Hi there,

Thanks for the library - useful stuff! :)

I have one suggestion for an improvement. When picking a picture from gallery for example, your code seems to copy the picture from it's original location, to the app's cache folder. This is great, except for one thing. I'm trying to later open an image viewer to view that picture (ACTION_VIEW intent), however, it's failing since outside apps don't have access to the cache folder in Android. (file:///data/user/0/<package>/cache/<folder name>/4d89c464-4b04-4c5e-ad6a-b3233790a36c).

I don't have this problem for images taken with the camera, since your code stores them in the app folder but on the sdcard (file:///storage/x/Android/data/<package>/files/Pictures/<folder name>/1b89f9d0-5c12-452b-aa13-5f3937ef5a20-906294538.jpg)

Any chance we can have an option to store the images picked into the publicly accessible app folder instead of the internal cache? Basically it would involve changing the folder returned here (https://github.com/jkwiecien/EasyImage/blob/master/library/src/main/java/pl/aprilapps/easyphotopicker/EasyImage.java#L51) based on a config. 

Thanks!

**Comment by jkwiecien** [comment]
Adding the stuff you requested in the upcoming release which should be during the next hour. Please check the doc part on this one though.

```        /**
         * Use this method if you want your picked gallery or documents pictures to be duplicated into public, other apps accessible, directory.
         * You'll have to take care of removing that file on your own after you're done with it. Use EasyImage.clearPublicTemp() method for that.
         * If you don't delete them they could show up in user galleries.
         *
         * @return modified Configuration object
         */
        public Configuration setCopyExistingPicturesToPublicLocation(boolean copyToPublicLocation)```
