### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;

### ISSUE THREAD

**Issue by mome13** [jkwiecien/EasyImage#215]
the error happened when I tried to initiate easyImage like below

`easyImage = new EasyImage.Builder(getMyContext())
                .setChooserTitle("choose pic")
                .setCopyImagesToPublicGalleryFolder(false)
                .setChooserType(ChooserType.CAMERA_AND_GALLERY)
                .setFolderName("packageName")
                .allowMultiple(false)
                .build();`

**Comment by tomx3000** [comment]
having the same problem, please may somebody address this ..

**Comment by tomx3000** [comment]
> the error happened when I tried to initiate easyImage like below
> 
> `easyImage = new EasyImage.Builder(getMyContext()) .setChooserTitle("choose pic") .setCopyImagesToPublicGalleryFolder(false) .setChooserType(ChooserType.CAMERA_AND_GALLERY) .setFolderName("packageName") .allowMultiple(false) .build();`


Solved
Add this
implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.61' 

worked for me
