### ISSUE TITLE
Configuration should not have a different output depending on builder methods call order.

### ISSUE THREAD

**Issue by GuillaumeDelente** [jkwiecien/EasyImage#22]
Example : 
```
        EasyImage.configuration(this)
                .saveInAppExternalFilesDir()
                .setImagesFolderName(FOLDER);
```

will lead to a different configuration than

```
        EasyImage.configuration(this)
                .setImagesFolderName(FOLDER)
                .saveInAppExternalFilesDir();
```

This is because `saveInAppExternalFilesDir()` and `saveInRootPicturesDirectory()` are both relying on the folder name, which in the first case is not set by the time `saveInAppExternalFilesDir()` is called.

**Comment by jkwiecien** [comment]
Expect it to be fixed in the incoming release
