### ISSUE TITLE
allowMultiple(true) isn't working for Samsung phones

### ISSUE THREAD

**Issue by YudizSumeet** [jkwiecien/EasyImage#224]
Hi greetings!

I'm not able to select multiple images from gallery using Samsung phones (tested on android 10 and 9). It returns only a single image.
The same code works for other phones.

**Comment by DJxLaurens** [comment]
Same problem! Is there already a solution?

**Comment by ChristianoBolla-Appwise** [comment]
I hate to be a bother, but this issue still persists in 3.2.0 for Samsung phones (Android 10).
