### ISSUE TITLE
not work with api30

### ISSUE THREAD

**Issue by iman2420** [jkwiecien/EasyImage#237]
`easyImage.openCameraForImage(this)` not working on API 30 emulator

and
`easyImage.canDeviceHandleGallery()` always false

**Comment by ncbb** [comment]
See: https://github.com/jkwiecien/EasyImage/issues/230

**Comment by Deepan27** [comment]
@iman2420 you found a solution for this?

**Comment by jkwiecien** [comment]
Duplicate
