### ISSUE TITLE
Crop Feature

### ISSUE THREAD

**Issue by TurKurT656** [jkwiecien/EasyImage#33]
Great Lib, TnQ for this amazing work.
is this lib supports crop feature when using camera?
if not can u add this?

TnQ

**Comment by Rainer-Lang** [comment]
Use SimpleImageCrop

**Comment by Rainer-Lang** [comment]
It's actually SimpleCropView
https://github.com/IsseiAoki/SimpleCropView

**Comment by jkwiecien** [comment]
I wanna keep this lib simple, that's why you should use external library for cropping as @Rainer-Lang suggested
