### ISSUE TITLE
Round overlay for camera possible?

### ISSUE THREAD

**Issue by Rainer-Lang** [jkwiecien/EasyImage#39]
Profileimages are normally round - therefore it would be great to show the user while taking a picture a round overlay.

**Comment by emmgfx** [comment]
I think that this should be a work un your terrain, this lib only does the
image picking.

**Comment by Rainer-Lang** [comment]
Any suggestions how to do this?

**Comment by emmgfx** [comment]
Check this:
https://github.com/hdodenhof/CircleImageView

Or this:
https://github.com/vinc3m1/RoundedImageView

Or any similar plugin.

2016-02-04 11:31 GMT+01:00 Rainer-Lang <notifications@github.com>:

> Any suggestions how to do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkwiecien/EasyImage/issues/39#issuecomment-179760245>.
>



-- 
Josep Viciana,
josep@viciana.me

**Comment by Rainer-Lang** [comment]
@emmgfx I think we have a little misunderstanding :)
I want an overlay WITHIN the camera - so the user looks THROUGH a circle. The outer areas are darkened (alpha). So the user could better see the later result.

Actually I'm using https://github.com/lopspower/CircularImageView
but this is for later usage.

**Comment by emmgfx** [comment]
oh, sorry.

In this case, what you are suggesting supposes that the lib or the app
contains a camera app and the user has selected it as default or through
the chooser.

I think that you need to do your own implementation...
http://developer.android.com/intl/es/guide/topics/media/camera.html#custom-camera

I hope that it helps you.


2016-02-04 19:18 GMT+01:00 Rainer-Lang <notifications@github.com>:

> @emmgfx <https://github.com/emmgfx> I think we have a little
> misunderstanding :)
> I want an overlay WITHIN the camera - so the user looks THROUGH a circle.
> The outer areas are darkened (alpha). So the user could better see the
> later result.
>
> Actually I'm using https://github.com/lopspower/CircularImageView
> but this is for later usage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkwiecien/EasyImage/issues/39#issuecomment-179978976>.
>



-- 
Josep Viciana,
josep@viciana.me

**Comment by jkwiecien** [comment]
Suggestions to make an own implementation are correct. Picasso library is one of the best that will help you with that.

**Comment by Rainer-Lang** [comment]
@jkwiecien What I want is like this here: http://stackoverflow.com/questions/15610419/circle-mask-effect
Could this really be done with Picasso?
