### ISSUE TITLE
The ACTION_IMAGE_CAPTURE intent will throw SecurityException if app targets M and declares CAMERA permission

### ISSUE THREAD

**Issue by yrom** [jkwiecien/EasyImage#4]
See notes on [ACTION_IMAGE_CAPTURE](https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE) and the [issue#188073](https://code.google.com/p/android/issues/detail?id=188073)

I test it can be replace with `ACTION_IMAGE_CAPTURE_SECURE` intent

**Comment by jkwiecien** [comment]
Solved, release will be available shortly.

**Comment by jkwiecien** [comment]
Solved with https://github.com/jkwiecien/EasyImage/commit/2f175985ddfa8dbe2c3797403a1de1234d6328fe

**Comment by pengrad** [comment]
Problem is ACTION_IMAGE_CAPTURE_SECURE requires API 17. 
So, you need to update minSdkVersion to 17. 
But I think it's better to create different intents depending on platform version.

**Comment by yrom** [comment]
@pengrad you're right.

**Comment by jkwiecien** [comment]
Fixed and released in 1.0.6 according to @pengrad advice.

**Comment by jkwiecien** [comment]
This only causes more troubles. ACTION_IMAGE_CAPTURE_SECURE doesn't work properly on many 17+ devices. For example HTC running lolipop or lenovo running kitkat. I think the best solution is having in mind that you need to request back CAMERA permission.
