### ISSUE TITLE
How to get only the path of images in the gallery ?

### ISSUE THREAD

**Issue by aresares** [jkwiecien/EasyImage#40]

**Comment by jkwiecien** [comment]
I don't quite get the question. Could you be more specific?

**Comment by aresares** [comment]
Sorry i don't speak english , how do i get only the path of the selected photo for example if the photo is stored in SDCARD/asd/asdss/asd.jpg how do i get this path?

i tried this i don't return the correct path  

@Override
            public void onImagePicked(File imageFile, EasyImage.ImageSource source) {
                //Handle the image
                Log.d("esx", "IMAGINE " + imageFile.getPath());

                //startUploadImage(imageFile.getPath());
            }

Thx

**Comment by jkwiecien** [comment]
imageFile.getPath() or imageFile().getFullPath()
That's not a question related to library. You got a lot to learn young one ;)
