### ISSUE TITLE
Internal fixed request code : flexibility issue with request differentiation

### ISSUE THREAD

**Issue by sfunke** [jkwiecien/EasyImage#41]
Since you set the requestCode fixed inside the openChooser... methods, I found no way how to differentiate between, say, 2 different image pick calls from the same activity.

In my case I want to pick either image 1 to populate ImageView A, or image 2 to populate ImageView 2.
Normally I would do this with different request codes, and handle the result appropriately.

Is there any way around it in the current configuration?

I know I can work around it with keeping track of the clicked button, but I was looking for a more stateless way.

Maybe you could introduce a request code parameter, which would then be binary combined with the internal request code, and on receiving the result, it would be resolved back and being passed into the callback?

**Comment by sfunke** [comment]
PS: nonetheless, great little helper library! :-)

**Comment by jkwiecien** [comment]
I solved it in the latest release, you must have missed it. Just check the readme - this is what the type param is for.

**Comment by sfunke** [comment]
Ah, great, yes I must have missed that. Thank you!
