### ISSUE TITLE
FAILED BINDER TRANSACTION

### ISSUE THREAD

**Issue by Rainer-Lang** [jkwiecien/EasyImage#50]
`EasyImage.openChooserWithGallery(this, "Image...", 0);` ---> `E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 17532784)`
But it seems that all is working fine.

**Comment by Rainer-Lang** [comment]
@jkwiecien Please have a look in this issue. v1.4 didn't help.

**Comment by Rainer-Lang** [comment]
@jkwiecien Do you get this bug too - or someone else?

**Comment by Rainer-Lang** [comment]
@jkwiecien If you have a snapshot to test - please let me know.

**Comment by Rainer-Lang** [comment]
1.4.1 also didn't solve the problem.

**Comment by jkwiecien** [comment]
But does it crash your app or just pop ups red in the logcat?

**Comment by hasnain-ahmad** [comment]
@Rainer-Lang @jkwiecien I am also getting the same error capturing the photo. Did you resolve the issue or any solution?

**Comment by winnerawan** [comment]
this issue still exist in v2.0.0
