### ISSUE TITLE
Failed to ensure directory

### ISSUE THREAD

**Issue by RiteshChandnani** [jkwiecien/EasyImage#54]
Log:
`Failed to ensure directory: /storage/sdcard1/Android/data/com.testapp.test/files/Pictures`
I have proper permissions declared in manifest.
I am running on : Android 4.4.4

This is happening only with device (as of now):
Xiaomi Redmi 2 Prime
[http://www.gsmarena.com/xiaomi_redmi_2_prime-7480.php](url)

**Comment by bkawakami** [comment]
+1

**Comment by jkwiecien** [comment]
Check it on 1.3.0
