### ISSUE TITLE
Manifest.permission.CAMERA

### ISSUE THREAD

**Issue by khramtsoff** [jkwiecien/EasyImage#55]
Demo project is missing Manifest.permission.CAMERA permission request. It'll be nice to have callbacks on Camera and Gallery selection, after calling openChooserWithGallery. In this case we will be able to check permissions separately: WRITE_EXTERNAL_STORAGE && CAMERA for camera and WRITE_EXTERNAL_STORAGE for gallery. Thanks.

**Comment by jkwiecien** [comment]
but the camera permission isnt necessary while you're using phone camera app and not embedding camera into your app
