### ISSUE TITLE
onPictureReturnedFromCamera  imageFile .length() ==0;

### ISSUE THREAD

**Issue by longtaoge** [jkwiecien/EasyImage#58]
Some phones     onPictureReturnedFromCamera      onImagePicked()

the imageFile.length()==0;

see   [https://github.com/longtoager/EasyImage.git](https://github.com/longtoager/EasyImage.git)

**Comment by nazarcybulskij** [comment]
Сan try to change      picture size or   picture  quality   ,  in some cases it should help .
Additionally, you can set the delay reading file   , new  Handler.postDelayed(new Runnable() , daley);  , but   is   duct tap  (( 
I tried  use  FileObserver  , but  this  way  dont work

**Comment by kaalpurush** [comment]
Image from camera is being saved as empty file in marshmallow. Works on lollipop on the very same device.

**Comment by jkwiecien** [comment]
Please ask to reopen if it's still the issue in the recent version
