### ISSUE TITLE
android.os.FileUriExposedException android N and later

### ISSUE THREAD

**Issue by swabbass** [jkwiecien/EasyImage#60]
Hey ,

i found this bug android.os.FileUriExposedException when opening the camera 

the bug as reffered here 
https://developer.android.com/reference/android/os/FileUriExposedException.html

is from N and later 

quick suggested fix is to change from file:// to content://

**Comment by winardi93** [comment]
hi @swabbass have you fixed this issue? i'm also developing on android 7 and got this error also

**Comment by aviadmini** [comment]
@winardi93 easy, temporary and limited solution is switching target SDK back to 23

Otherwise app needs to define a file provider to share permission to other app components.

**Comment by wangjunemse** [comment]
for SDK version 24 or higher, Google encourages to use FileProvider instead.  this topic is discussed here:
http://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by jkwiecien** [comment]
Is this still a thing? Library is using FileProvider for quite some time? Reopen if it's still an issue

**Comment by baati** [comment]
Yes it is still an issue. And this may be one of the solution if  not already implemented .
https://developer.android.com/reference/android/os/FileUriExposedException.html

**Comment by kksingla** [comment]
replace  android:name="android.support.v4.content.FileProvider"  with android:name=".MyFileProvider"

public class MyFileProvider extends FileProvider {
}
