### ISSUE TITLE
Remove Current Image!

### ISSUE THREAD

**Issue by khaledkhj** [jkwiecien/EasyImage#63]
I don't know if this suggestion will be possible or easy to implement,
but it will be great if we have an extra option on the picker to remove the current image selected!?

**Comment by jkwiecien** [comment]
@rciovati What do you think? Now when there is FileProvider involved.

**Comment by rciovati** [comment]
Well, such a feature could be implemented quite easily even with the new FileProvider mechanism but IHMO I'd keep the library as simple as possible and let the clients to implement the logic they need. In this case it wouldn't be difficult for the client app to save the File path in the `onImagePicked ` method and delete it when needed.

**Comment by jkwiecien** [comment]
I agree
