### ISSUE TITLE
Can't take Image from Camera in android 6.0

### ISSUE THREAD

**Issue by sonvp** [jkwiecien/EasyImage#73]
-  Hi. I meet bug when try take Image from camera. 
- Device test: 
1. Sony Z3 Dual
2. Version 6.0.1 
- This is my Log

System.err: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/pl.aprilapps.easyphotopicker.sample/cache/EasyImage/7f92ccdc-1d35-41f8-89e4-84b252ed1a5b-1112704913.jpg
09-20 13:46:13.656 2424-2424/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:679)
09-20 13:46:13.656 2424-2424/pl.aprilapps.easyphotopicker.sample W/System.err:     at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:378)
09-20 13:46:13.656 2424-2424/pl.aprilapps.easyphotopicker.sample W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.createCameraPictureFile(EasyImage.java:54)
09-20 13:46:13.656 2424-2424/pl.aprilapps.easyphotopicker.sample W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.createCameraIntent(EasyImage.java:79)
09-20 13:46:13.656 2424-2424/pl.aprilapps.easyphotopicker.sample W/System.err:     at pl.aprilapps.easyphotopicker.EasyImage.openCamera(EasyImage.java:229)
09-20 13:46:13.657 2424-2424/pl.aprilapps.easyphotopicker.sample W/System.err:     at pl.aprilapps.easyphotopicker.sample.MainActivity.onTakePhotoClicked(MainActivity.java:68)
09-20 13:46:13.657 2424-2424/pl.aprilapps.easyphotopicker.sample W/System.err:     at pl.aprilapps.easyphotopicker.sample.MainActivity$$ViewBinder$1.doClick

**Comment by allonmj** [comment]
For what its worth, I had the same problem and figured out that I had a 'filepaths.xml' in my own app which was overriding the EasyImage one.  Simply renaming mine to something like 'my_filepaths.xml' fixed it for me.
