### ISSUE TITLE
Using EasyImage.handleActivityResult in Fragment

### ISSUE THREAD

**Issue by sedarcode** [jkwiecien/EasyImage#75]
Hi all,

My problem is using EasyImage in fragment and most problem with sample code in fragment
I dont know how figure out EasyImage.handleActivityResult(requestCode, resultCode, data, this, new DefaultCallback() because 3th parameters need activity .
if someone solved this problem please tell me

**Comment by CapitainOats** [comment]
Hi you, 

Well, this isnt exactly issue. Anyway I created example app, that is using EasyImage inside fragment. So be sure to check it out https://github.com/CapitainOats/EasyImageTutorial , and have a nice day :) .

**Comment by jkwiecien** [comment]
thanks @CapitainOats

**Comment by Bob33700** [comment]
Hello,
It seems that doesn't work for me...
My fragment is :
 `	public class DocumentAddFragment extends DialogFragment {....`

I call EasyImage like this : 
`	EasyImage.openGallery(DocumentAddFragment.this, -1);`

and in my fragment, my 'onActivityResult' starts like this : 
```
	@Override
	public void onActivityResult(int requestCode, int resultCode, Intent data) {
		super.onActivityResult(requestCode, resultCode, data);
		Log.d("onActivityResult", Integer.toString(requestCode));
...
```
but my 'onActivityResult' is never called (no log)
If put an 'onActivityResult' in the Activity, this one is called even if I called EasyImage with 'DocumentAddFragment.this' as first parameter.

Any idea please ???
