### ISSUE TITLE
saveInRootPicturesDirectory("name") doesn't work with library update

### ISSUE THREAD

**Issue by jeanvallon** [jkwiecien/EasyImage#82]
Hello,

I updated the library to the version 1.4.0 that you released Nov 11th.
Unfortunately, my pictures won't save in the custom directory anymore.
Here is my code :

```
private void initConfigEasyImage() {
            EasyImage.clearConfiguration(context);
            EasyImage.configuration(context)
                             .setImagesFolderName("Custom directory")
                             .saveInRootPicturesDirectory();
    }
```

Please note that I already had a problem before I updated the library (I had version 1.2.4) : The pictures I took were saved both in the 'Pictures' folder of my phone and 'Pictures/Custom Directory' folder.
I thought that updating the library would solve the problem but now it's worse : it's still saved in the 'Pictures' folder but NOT in the 'Pictures/Custom Directoy' folder.

Thank you very much for your help.

**Comment by jeanvallon** [comment]
Actually I was duplicating the picture myself, that's why a picture saved in 'Pictures' folder.

**Comment by jkwiecien** [comment]
Please clarify is it still a problem or which part is still a problem
