### ISSUE TITLE
NullPointerException when only one image is selected

### ISSUE THREAD

**Issue by rafaldziuryk** [jkwiecien/EasyImage#84]
v 1.4

When I called:
EasyImage.openGallery (this, 0, true);

I've got NullPointerException

`ClipData clipData = data.getClipData();`
`for (int i = 0; i < clipData.getItemCount(); i++) {`
`Uri uri = clipData.getItemAt(i).getUri();`
`File file = EasyImageFiles.pickedExistingPicture(activity, uri);`
`files.add(file);`
`}`

`clipData` is null.

Problem occurs when you selected only one image from gallery.

**Comment by wenbinke** [comment]
I have same issue

**Comment by jkwiecien** [comment]
Merged, releasing it
