### ISSUE TITLE
OpenChooserWithGallery returns just one photo from gallery

### ISSUE THREAD

**Issue by vycius** [jkwiecien/EasyImage#90]
After calling `OpenChooserWithGallery` and choosing multiple photos from gallery only the first one is returned. 
Steps to reproduce:
1. Call `EasyImage.openChooserWithGallery(this, getString(R.string.add_photos), 0);`
2. `onImagesPicked` will contain just one file in `imageFiles`. 

Why it happens. 
Internally `EasyImage::openChooserWithGallery` calls `createChooserIntent` with `showGallery = true` and `GalleryIntent` with `allowMultiple` is created. 

In `handleActivityResult` else condition will be picked https://github.com/jkwiecien/EasyImage/blob/master/library/src/main/java/pl/aprilapps/easyphotopicker/EasyImage.java#L291 and `onPictureReturnedFromDocuments` will be called. This method includes just one picture. 

Library version 1.4.1

**Comment by rafaldziuryk** [comment]
https://github.com/jkwiecien/EasyImage/pull/92 should fix this error

**Comment by jkwiecien** [comment]
try 1.4.2
